# Generated by Django 4.0.4 on 2022-06-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lecturer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reg_no',
            field=models.CharField(max_length=15, unique=True, verbose_name='Identification Number'),
        ),
    ]
